hello = "Hello!"
hello-fallback = "Hello not German!"

[args]
hello-args = "Hello {name}!"

[nested]
hello-nested = "Hello nested!"

[nested.deeper-nested]
hello-deeper-nested = "Hello deeper nested!"